import Head from 'next/head';
import Avatar from '../components/Avatar.js';
import { MicroIcon, ViewGridIcon } from '@heroicons/react/solid';
import Image from 'next/Image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/** Header */}
      <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
        {/** Left */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>
        {/** Right */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>
          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer' />
          <Avatar url='https://cdn.icon-icons.com/icons2/1879/PNG/512/iconfinder-8-avatar-2754583_120515.png' />
        </div>
      </header>
      {/** Body */}
      <form>
        <Image
          width={300}
          height={100}
          src='https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
        />
      </form>
      {/** Footer */}
      <footer></footer>
    </div>
  );
}
